In [1]:
import pandas as pd
import numpy as np

In [2]:
np.random.seed(42)

In [3]:
data = {'x1':[1,1,0,0],
        'x2':[0,1,0,1],
        'y':[0,0,1,1]}


df = pd.DataFrame(data)

In [58]:
# Create perceptron class
class Perceptron:
    """ Base perceptron class """
    
    def __init__(self, n_iter=100):
        self.n_iter = n_iter
        
    def sigmoid(self, x):
        return 1/(1+np.exp(-x))
    
    def sigmoid_derivative(self, x):
        fx = self.sigmoid(x)
        return fx * (1 - fx)
    
    def fit(self, X, y):
        
        self.weights = 2 * np.random.random((X.shape[1], 1)) - 1
        
        for i in range(self.n_iter):
            # Feed Forward
            weighted_sum = np.dot(X, self.weights)
            activated_output = self.sigmoid(weighted_sum)
            
            # Backpropagation
            error = np.array([y]).T - activated_output
            adjustments = error * self.sigmoid_derivative(weighted_sum)
            
            self.weights = self.weights + np.dot(X.T, adjustments)
    
    def predict(self, X):
        weighted_sum = np.dot(X, self.weights)
        activated_output = self.sigmoid(weighted_sum)
        return activated_output
        

In [59]:
model = Perceptron()

In [60]:
X.shape[1]

2

In [62]:
X = df[['x1', 'x2']].values
y = df['y'].values

model.fit(X, y)

In [63]:
model.weights

array([[-3.80350542],
       [ 1.76682152]])

In [64]:
model.predict(np.array([1,1]))

array([0.11540483])

In [68]:
y_pred = model.predict(np.array([[1,1], [1,0], [0,1], [0,0]]))

In [69]:
y_pred

array([[0.11540483],
       [0.02180637],
       [0.85406195],
       [0.5       ]])

In [70]:
[1 if x >= .5 else 0 for x in y_pred]

[0, 0, 1, 1]

In [78]:
class BasicNN:
    """ Base perceptron class """
    
    def __init__(self, inputs=8, hidden=4, output=1, n_iter=100):
        self.n_iter = n_iter
        self.inputs = inputs
        self.hidden_nodes = hidden
        self.output_nodes = output
        
        self.weights1 = 2 * np.random.random((self.inputs, self.hidden_nodes)) - 1
        self.weights2 = 2 * np.random.random((self.hidden_nodes, self.output_nodes)) - 1
        
    def sigmoid(self, x):
        return 1/(1+np.exp(-x))
    
    def sigmoid_derivative(self, x):
        fx = self.sigmoid(x)
        return fx * (1 - fx)
    
    def fit(self, X, y):
        
        for i in range(self.n_iter):
            # Feed Forward
            
            # From input to hidden layer
            weighted_sum = np.dot(X, self.weights1)
            activated_hidden = self.sigmoid(weighted_sum)
            # From hidden to output
            weighted_sum_2 = np.dot(activated_hidden, self.weights2)
            activated_output = self.sigmoid(weighted_sum_2)
            
            # Backpropagation
            stage2_error = np.array([y]).T - activated_output
            stage2_adj = stage2_error * self.sigmoid_derivative(weighted_sum_2)
            
            stage1_error = np.dot(stage2_adj, self.weights2.T)
            stage1_adj = stage1_error * self.sigmoid_derivative(weighted_sum)
            
            self.weights1 = self.weights1 + np.dot(X.T, stage1_adj)
            self.weights2 = self.weights2 + np.dot(activated_hidden.T, stage2_adj)
    
    def predict(self, X):
        weighted_sum = np.dot(X, self.weights1)
        activated_hidden = self.sigmoid(weighted_sum)
        weighted_sum_2 = np.dot(activated_hidden, self.weights2)
        activated_output = self.sigmoid(weighted_sum_2)
        return activated_output

In [79]:
model_2 = BasicNN(inputs=2, hidden=4, output=1)

In [80]:
model_2.fit(X,y)

In [81]:
y_pred_2 = model_2.predict(np.array([[1,1], [1,0], [0,1], [0,0]]))
y_pred_2

array([[0.15373401],
       [0.10287665],
       [0.92335871],
       [0.80945783]])

In [82]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')

In [83]:
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [84]:
from sklearn.preprocessing import MinMaxScaler


In [91]:
features = list(diabetes)[:-1]
target = 'Outcome'

In [92]:
scaler = MinMaxScaler()

X_scaled = scaler.fit_transform(diabetes[features])
y = diabetes[target]

In [94]:
X_scaled.shape

(768, 8)

In [96]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.25, random_state=42)

In [97]:
from sklearn.metrics import accuracy_score

model = Perceptron()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
y_pred = [1 if x >= 0.5 else 0 for x in y_pred]

accuracy = accuracy_score(y_pred, y_test)

In [98]:
accuracy

0.640625

In [108]:
model_2 = BasicNN(inputs=8, hidden=128, output=1, n_iter=1000)
model_2.fit(X_train, y_train)

y_pred = model_2.predict(X_test)

In [110]:
data = dict({'x1': [0, 0, 1, 0, 1, 1, 0], 
             'x2': [0, 1, 0, 1, 0, 1, 0], 
             'x3': [1, 1, 1, 0, 0, 1, 0], 
             'y': [0, 1, 1, 1, 1, 0, 0]
            })

xor_gate = pd.DataFrame.from_dict(data)

# XOR Gate

In [111]:
features = xor_gate[['x1', 'x2', 'x3']]
target = xor_gate['y']

In [115]:
model = BasicNN(inputs=3, hidden=4, output=1, n_iter=1000)
model.fit(features, target)
model.predict(features)

array([[0.01136585],
       [0.94756583],
       [0.96104478],
       [0.9558584 ],
       [0.97100052],
       [0.06483102],
       [0.06993891]])